[profile.default]
evm_version = "prague"
extra_output_files = ["abi"]
fs_permissions = [{ access = "read", path = "./test/fixtures" }]
libs = ["dependencies", "lib", "node_modules"]
optimizer = true
optimizer_runs = 9999
out = "out"
remappings = [
  # for local
  "@mitosis/=dependencies/mitosis-1.1.1/",
  "@openzeppelin-contracts-5.2.0/=dependencies/@openzeppelin-contracts-5.2.0/",
  "@openzeppelin-contracts-upgradeable-5.2.0/=dependencies/@openzeppelin-contracts-upgradeable-5.2.0/",
  "@oz/=dependencies/@openzeppelin-contracts-5.2.0/",
  "@ozu/=dependencies/@openzeppelin-contracts-upgradeable-5.2.0/",
  "@solady/=dependencies/solady-0.1.21/src",
  "@sp1/=dependencies/succinctlabs-sp1-contracts-5.0.0/contracts/src",
  "@std/=dependencies/forge-std-1.9.6/src",
  "@stub/=dependencies/stub-0.0.1/",

  # for dependencies
  "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.2.0/",
  "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.2.0/",

  # for sp1-contracts (git submodules not cloned by Soldeer)
  "dependencies/succinctlabs-sp1-contracts-5.0.0/contracts/lib/openzeppelin-contracts/contracts/=dependencies/@openzeppelin-contracts-5.2.0/",
]
solc = "0.8.29"
src = "src"

[fmt]
bracket_spacing              = true
line_length                  = 100
multiline_func_header        = 'params_first'
quote_style                  = "single"
single_line_statement_blocks = 'single'
tab_width                    = 2

[lint]
exclude_lints = ["mixed-case-function", "mixed-case-variable"]

[soldeer]
remappings_generate   = false
remappings_location   = "config"
remappings_regenerate = false

[dependencies]
"@openzeppelin-contracts"             = "5.2.0"
"@openzeppelin-contracts-upgradeable" = "5.2.0"
forge-std                             = "1.9.6"
mitosis                               = "1.1.1"
solady                                = "0.1.21"
stub                                  = "0.0.1"
succinctlabs-sp1-contracts            = { version = "5.0.0", git = "https://github.com/succinctlabs/sp1-contracts.git", tag = "v5.0.0" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
